// generated by Fast Light User Interface Designer (fluid) version 1.0401

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Output.H>
extern Fl_Output *counter_widget;
#include <FL/Fl_Button.H>
#endif
